- name: nvmのインストール
  git:
    repo: https://github.com/creationix/nvm.git
    dest: "{{ nvm_path }}"

- name: rbenv.sh に書き込んだ設定を読み込む
  become_user: ec2-user
  shell: source ~/.nvm/nvm.sh

- name: 環境変数PATHにrbenvのパスを設定
  become_user: ec2-user
  copy:
   src: ./files/nvm
   dest: "{{ bash_profile_path }}"

- name: bash_profile に書き込んだ設定を読み込む
  become_user: ec2-user
  shell: source ~/.bash_profile

- name: nvmのパーミッション変更
  file:
    path="{{ nvm_path }}"
    state=directory
    recurse=yes
    owner=ec2-user
    group=wheel

- name: node.jsのインストール
  become_user: ec2-user
  shell: bash -lc "nvm install {{ nvm_version }}"

- name: 作業ディレクトリ作成
  become_user: ec2-user
  file:
    path="{{ rails_dir }}"
    state=directory

- name: Install bundler
  become_user: ec2-user
  shell: bash -lc "gem install bundler"
  args:
    chdir: "{{ rails_dir }}"

- name: Gemfileの存在を確認
  stat:
    path: "{{ rails_dir }}/Gemfile"
  register: Gemfile_chk

- name: init bundler
  become_user: ec2-user
  shell: bash -lc "bundle init"
  args:
    chdir: "{{ rails_dir }}"
  when: not Gemfile_chk.stat.exists

- name: Gemfileの修正
  become_user: ec2-user
  lineinfile:
    path: "{{ rails_dir }}/Gemfile"
    regexp: '# gem "rails"'
    line: 'gem "rails", "{{ rails_version }}"'

- name: railsのインストール
  become_user: ec2-user
  shell: bash -lc "bundle install"
  args:
    chdir: "{{ rails_dir }}"

- name: railsの作業ディレクトリ作成
  become_user: ec2-user
  shell: bash -lc "bundle exec rails _{{ rails_version }}_ new . -d mysql -f"
  args:
    chdir: "{{ rails_dir }}"

- name: bundle update sprockets
  become_user: ec2-user
  shell: bash -lc "bundle update sprockets"
  args:
    chdir: "{{ rails_dir }}"

- name: bundle install
  become_user: ec2-user
  shell: bash -lc "bundle install"
  args:
    chdir: "{{ rails_dir }}"

- name: database.ymlを修正
  become_user: ec2-user
  copy:
   src: ./files/database.yml
   dest: "{{ rails_file_path }}"

- name: bundle exec rails db:create
  become_user: ec2-user
  shell: bash -lc "bundle exec rails db:create"
  args:
    chdir: "{{ rails_dir }}"

- name: bundle exec rails db:migrate
  become_user: ec2-user
  shell: bash -lc "bundle exec rails db:migrate"
  args:    
    chdir: "{{ rails_dir }}"
